/**
 * Worker entry point. Wraps the OpenNext-generated worker (built into .open-next/) and adds a
 * `scheduled` handler for Cloudflare Cron Triggers (see "triggers" in wrangler.jsonc).
 *
 * The cron calls the app's own /api/cron/keepalive route through the WORKER_SELF_REFERENCE
 * service binding, authenticated with the CRON_SECRET Worker secret, so all the keep-alive
 * logic (and its logging) stays inside the Next.js app.
 */
// @ts-ignore — generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

export default {
	fetch: handler.fetch,

	/** @param {ScheduledController} controller @param {any} env @param {ExecutionContext} ctx */
	async scheduled(controller, env, ctx) {
		ctx.waitUntil(
			(async () => {
				const res = await env.WORKER_SELF_REFERENCE.fetch("https://merkadoph-opennext.workers.dev/api/cron/keepalive", {
					method: "POST",
					headers: { authorization: `Bearer ${env.CRON_SECRET}`, "x-cron": controller.cron },
				});
				const body = await res.text();
				if (!res.ok) throw new Error(`Keep-alive cron failed (${res.status}): ${body}`);
				console.log(`Keep-alive cron ok: ${body}`);
			})(),
		);
	},
};
